### ISSUE TITLE
Falied to properly initialize Processor

### ISSUE THREAD

**Issue by naudor** [linksmart/nifi-opc-ua-bundles#3]
Hi.

First, I want to give you the tanks you for this implementation.
By other hand, I have problems with the SubscribeOPCNodes. When I try to start apears a error:
"Falied to properly initialize Processor" aparently for Too many subscription, but in the tag list file only have wrote only one node
[CanalsSubscritsUaCPPServer.txt](https://github.com/linksmart/nifi-opc-ua-bundles/files/3540121/CanalsSubscritsUaCPPServer.txt)
![image](https://user-images.githubusercontent.com/9480362/63675934-2fd0d280-c7ea-11e9-8a00-975c0518eb0f.png)

The configuration of the processor:
![image](https://user-images.githubusercontent.com/9480362/63695044-15ade900-c818-11e9-9428-c71e25f702a9.png)
![image](https://user-images.githubusercontent.com/9480362/63695074-265e5f00-c818-11e9-8c4d-e22b4f9f331f.png)
![image](https://user-images.githubusercontent.com/9480362/63695109-3bd38900-c818-11e9-9a33-ec52aec69d5b.png)

The configuration of the service:
![image](https://user-images.githubusercontent.com/9480362/63695164-5ad21b00-c818-11e9-8114-cf112dace000.png)

I haven't problems with the same tag list file on GetOPCData.

Can you help me?

Thanks a lot

**Comment by dschowta** [comment]
Dear @naudor ,

Sorry that we did not help you on this on time as we are not dedicatedly not working on this repository. 
I see that you have closed the issue. Does that mean you have figured out a solution?
If so could you share others too how you handled it? 

Thanks,
Shreekantha

**Comment by naudor** [comment]
It's difficult to say. The procesors througth diferents errors
(initialitation, too many connections, blank results...) , but work with
specific parameters. I'm not sure about the problems are because wrong opc
server configuration, somethung wrong on the NIFI processor code or simply
work's correctly but I'm expect another behavior.

Thanks for all.
